In [1]:
import pandas
from konlpy.tag import Komoran
from gensim.models import word2vec
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import string
import re
import sys

In [2]:
#파일 읽어오기
file = open('./sonagi.txt','r',encoding='utf-8')
line = file.read()
lines = line[:19*350]

#장(chapter)마다 나눔
sentences = re.split('(?<=[2-9]\n)|(?<=[0-9][0-9]\n)|(?<=[0-9][0-9][0-9]\n)', line)
# if len(sentences) < 2:
#     sentences = re.split('(?<=[0-9]장)|(?<=[0-9][0-9]장)', lines)

#Komoran 형태소 분석을 위한 전처리
sent=[]
for stuff in sentences:
        stuff= "\n".join([s for s in stuff.split("\n") if s])
        stuff="".join([s for s in stuff.splitlines(True) if s.strip()])
        sent.append(stuff)

In [3]:
komoran = Komoran(userdic='./user_dic.txt')

In [4]:
#형태소분석
sentences_tag = []
for sentence in sent:
    morph = komoran.pos(sentence)
    sentences_tag.append(morph)

In [5]:
#명사 추출
noun_adj_list=[]
noun_adj=[]
#komoran
for sentence1 in sentences_tag:
    noun_adj=[]
    for word, tag in sentence1:
        if word in '왕' or len(word)>1:
            if tag in ['NNP']: #komoran
                word = word.replace(" ","")
                noun_adj.append(word)
    noun_adj_list.append(noun_adj)

In [6]:
print(noun_adj_list)

[['소나기', '황순원', '소년', '시네', '소녀', '서울', '소녀', '돌아오는길', '소년', '분홍', '스웨터', '고기', '소녀', '조약돌', '바보', '조약돌', '소년', '소녀', '안고', '천한', '소녀', '소녀', '소년', '조약돌', '소년', '조약돌', '소녀', '소녀', '소년', '주머니', '조약돌', '버릇', '소년', '소년', '놀라', '소년', '달리기', '디딤돌', '메밀', '액체', '코피', '소년', '코피', '바보', '바보', '소녀', '여태', '조개', '소녀', '소녀', '비단', '조개', '이름', '소녀', '소년', '가야', '너머', '우리', '서울', '소풍', '소녀', '바보', '바보', '허수아비', '참새', '참새', '허수아비', '허수아비', '소녀', '보조개', '허수아비', '소년', '집안일', '소녀', '메뚜기', '소년', '독수리', '독수리', '독수리', '돌고', '소녀', '허수아비', '허수아비', '도랑', '원두막', '참외', '참외', '수박', '하나', '참외', '그루', '물어', '손톱', '소녀', '산이', '단풍', '들국화', '싸리', '도라지', '도라지', '양산', '마타리', '소녀', '마타리', '양산', '보조개', '소년', '소녀', '하나', '골짜기', '말라가', '서울', '놀라', '소년', '제가', '소녀', '소년', '소년', '이거', '송진', '송아지', '바투', '송아지', '소녀', '분홍', '스웨터', '남색', '안고', '예서', '농부', '하나', '송아지', '송아지', '상하면', '농부', '소녀', '송아지', '소나기', '구름', '장이', '사면', '떡갈나무', '빗방울', '빗방울', '원두막', '원두막', '기둥', '지붕', '소녀', '무명', '저고리', '소녀', '소녀', '고온', '송이', '곳도', '수수', 

In [7]:
############# TF-IDF###################

In [8]:
# tf-idf 전처리
ad_text=[]
b=''
for i in noun_adj_list:
    a=" ".join(i).split(",")
    print(a)
    b=''.join(a)
    print(b)
    ad_text.append(b)

['소나기 황순원 소년 시네 소녀 서울 소녀 돌아오는길 소년 분홍 스웨터 고기 소녀 조약돌 바보 조약돌 소년 소녀 안고 천한 소녀 소녀 소년 조약돌 소년 조약돌 소녀 소녀 소년 주머니 조약돌 버릇 소년 소년 놀라 소년 달리기 디딤돌 메밀 액체 코피 소년 코피 바보 바보 소녀 여태 조개 소녀 소녀 비단 조개 이름 소녀 소년 가야 너머 우리 서울 소풍 소녀 바보 바보 허수아비 참새 참새 허수아비 허수아비 소녀 보조개 허수아비 소년 집안일 소녀 메뚜기 소년 독수리 독수리 독수리 돌고 소녀 허수아비 허수아비 도랑 원두막 참외 참외 수박 하나 참외 그루 물어 손톱 소녀 산이 단풍 들국화 싸리 도라지 도라지 양산 마타리 소녀 마타리 양산 보조개 소년 소녀 하나 골짜기 말라가 서울 놀라 소년 제가 소녀 소년 소년 이거 송진 송아지 바투 송아지 소녀 분홍 스웨터 남색 안고 예서 농부 하나 송아지 송아지 상하면 농부 소녀 송아지 소나기 구름 장이 사면 떡갈나무 빗방울 빗방울 원두막 원두막 기둥 지붕 소녀 무명 저고리 소녀 소녀 고온 송이 곳도 수수 라다 소년 소년 안고 소녀 소년 돌리지 소년 햇빛 도랑 보니 불어 소년 소녀 소년 구름 소녀 달려와 소년 주머니 조약돌 소년 소녀 소나기 인제 하도 분홍 스웨터 진흙 보조개 소년 스웨터 도랑 소년 소녀 소년 소년 소년 사해 초시 손자 서울 그런지 소녀 소녀 돌아오는길 소년 소년 단맛 소년 호두 호두 송이 호두 내리 돌아오는길 그늘 그늘 호두 송이 근동 호두 바보 바보 안고 안고 이만 하면 망태기 서당 초시 수탉 허허 실속 소년 쇠파리 소년 서당 양평읍 소년 주머니 호두 소년 보나 초시 아니야 대대로 바느질 안고 복이 시네 기전']
소나기 황순원 소년 시네 소녀 서울 소녀 돌아오는길 소년 분홍 스웨터 고기 소녀 조약돌 바보 조약돌 소년 소녀 안고 천한 소녀 소녀 소년 조약돌 소년 조약돌 소녀 소녀 소년 주머니 조약돌 버릇 소년 소년 놀라 소년 달리기 디딤돌 메밀 액체 코피 소년 코피 바보 바보 소녀 여태 조개 소녀 소녀 비단 조개 이

In [9]:
print(ad_text)

['소나기 황순원 소년 시네 소녀 서울 소녀 돌아오는길 소년 분홍 스웨터 고기 소녀 조약돌 바보 조약돌 소년 소녀 안고 천한 소녀 소녀 소년 조약돌 소년 조약돌 소녀 소녀 소년 주머니 조약돌 버릇 소년 소년 놀라 소년 달리기 디딤돌 메밀 액체 코피 소년 코피 바보 바보 소녀 여태 조개 소녀 소녀 비단 조개 이름 소녀 소년 가야 너머 우리 서울 소풍 소녀 바보 바보 허수아비 참새 참새 허수아비 허수아비 소녀 보조개 허수아비 소년 집안일 소녀 메뚜기 소년 독수리 독수리 독수리 돌고 소녀 허수아비 허수아비 도랑 원두막 참외 참외 수박 하나 참외 그루 물어 손톱 소녀 산이 단풍 들국화 싸리 도라지 도라지 양산 마타리 소녀 마타리 양산 보조개 소년 소녀 하나 골짜기 말라가 서울 놀라 소년 제가 소녀 소년 소년 이거 송진 송아지 바투 송아지 소녀 분홍 스웨터 남색 안고 예서 농부 하나 송아지 송아지 상하면 농부 소녀 송아지 소나기 구름 장이 사면 떡갈나무 빗방울 빗방울 원두막 원두막 기둥 지붕 소녀 무명 저고리 소녀 소녀 고온 송이 곳도 수수 라다 소년 소년 안고 소녀 소년 돌리지 소년 햇빛 도랑 보니 불어 소년 소녀 소년 구름 소녀 달려와 소년 주머니 조약돌 소년 소녀 소나기 인제 하도 분홍 스웨터 진흙 보조개 소년 스웨터 도랑 소년 소녀 소년 소년 소년 사해 초시 손자 서울 그런지 소녀 소녀 돌아오는길 소년 소년 단맛 소년 호두 호두 송이 호두 내리 돌아오는길 그늘 그늘 호두 송이 근동 호두 바보 바보 안고 안고 이만 하면 망태기 서당 초시 수탉 허허 실속 소년 쇠파리 소년 서당 양평읍 소년 주머니 호두 소년 보나 초시 아니야 대대로 바느질 안고 복이 시네 기전']


In [16]:
if len(sentences) < 2 :
    ad_text = noun_adj

In [17]:
ad_text.remove('안고')

In [19]:
print(ad_text)

['소나기', '황순원', '소년', '시네', '소녀', '서울', '소녀', '돌아오는길', '소년', '분홍', '스웨터', '고기', '소녀', '조약돌', '바보', '조약돌', '소년', '소녀', '천한', '소녀', '소녀', '소년', '조약돌', '소년', '조약돌', '소녀', '소녀', '소년', '주머니', '조약돌', '버릇', '소년', '소년', '놀라', '소년', '달리기', '디딤돌', '메밀', '액체', '코피', '소년', '코피', '바보', '바보', '소녀', '여태', '조개', '소녀', '소녀', '비단', '조개', '이름', '소녀', '소년', '가야', '너머', '우리', '서울', '소풍', '소녀', '바보', '바보', '허수아비', '참새', '참새', '허수아비', '허수아비', '소녀', '보조개', '허수아비', '소년', '집안일', '소녀', '메뚜기', '소년', '독수리', '독수리', '독수리', '돌고', '소녀', '허수아비', '허수아비', '도랑', '원두막', '참외', '참외', '수박', '하나', '참외', '그루', '물어', '손톱', '소녀', '산이', '단풍', '들국화', '싸리', '도라지', '도라지', '양산', '마타리', '소녀', '마타리', '양산', '보조개', '소년', '소녀', '하나', '골짜기', '말라가', '서울', '놀라', '소년', '제가', '소녀', '소년', '소년', '이거', '송진', '송아지', '바투', '송아지', '소녀', '분홍', '스웨터', '남색', '안고', '예서', '농부', '하나', '송아지', '송아지', '상하면', '농부', '소녀', '송아지', '소나기', '구름', '장이', '사면', '떡갈나무', '빗방울', '빗방울', '원두막', '원두막', '기둥', '지붕', '소녀', '무명', '저고리', '소녀', '소녀', '고온', '송이', '곳도', '수수', '라다', '

In [42]:
#TF
vector = CountVectorizer()
print(vector.fit_transform(ad_text).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
{'소나기': 57, '황순원': 108, '소년': 59, '시네': 71, '소녀': 58, '서울': 56, '돌아오는길': 27, '분홍': 47, '스웨터': 70, '고기': 1, '조약돌': 91, '바보': 40, '천한': 98, '주머니': 92, '버릇': 42, '놀라': 15, '달리기': 20, '디딤돌': 29, '메밀': 36, '액체': 76, '코피': 100, '여태': 79, '조개': 90, '비단': 49, '이름': 84, '가야': 0, '너머': 14, '우리': 81, '소풍': 60, '허수아비': 105, '참새': 96, '보조개': 45, '집안일': 95, '메뚜기': 35, '독수리': 24, '돌고': 25, '도랑': 23, '원두막': 82, '참외': 97, '수박': 67, '하나': 101, '그루': 8, '물어': 38, '손톱': 62, '산이': 53, '단풍': 18, '들국화': 28, '싸리': 73, '도라지': 22, '양산': 77, '마타리': 32, '골짜기': 3, '말라가': 33, '제가': 89, '이거': 83, '송진': 65, '송아지': 63, '바투': 41, '남색': 12, '안고': 75, '예서': 80, '농부': 16, '상하면': 54, '구름': 5, '장이': 87, '사면': 51, '떡갈나무': 30, '빗방울': 50, '기둥': 10, '지붕': 93, '무명': 37, '저고리': 88, '고온': 2, '송이': 64, '곳도': 4, '수수': 68, '라다': 31, '돌리지': 26, '햇빛': 104, '보니': 44, '불어': 48, '달려와': 19, '인제': 86, '하도': 102, '진흙': 94, 

In [43]:
# TF-IDF 설정
tfidf = TfidfVectorizer(max_features = 5, max_df=0.95, min_df=0) #(max_features = 5) <- 상위 5개만 추출

#generate tf-idf term-document matrix
A_tfidf_sp = tfidf.fit_transform(ad_text)

In [44]:
tfidf_dict = tfidf.get_feature_names()
# print(tfidf_dict) 

In [45]:
# 값이 적을수록 다른 문서에서 자주 언급
print(tfidf.vocabulary_)

{'소년': 2, '소녀': 1, '조약돌': 3, '바보': 0, '허수아비': 4}


In [24]:
# counter 위주
# wh=[]
# for i in vector.vocabulary_:
#     if i in tfidf_dict:
#         wh.append(i)
#         print(i)
# print(wh)

# import collections 
# container = collections.Counter()
# container.update(noun_adj_all)

# for k,v in container.items():
#     if k in tfidf_dict:
#         print(k,":",v)

In [25]:
#############Word2Vec######################

In [26]:
sents = [doc.split(" ") for doc in ad_text] #Word2Vec 을 위한 전처리

In [27]:
print(sents)

[['소나기'], ['황순원'], ['소년'], ['시네'], ['소녀'], ['서울'], ['소녀'], ['돌아오는길'], ['소년'], ['분홍'], ['스웨터'], ['고기'], ['소녀'], ['조약돌'], ['바보'], ['조약돌'], ['소년'], ['소녀'], ['천한'], ['소녀'], ['소녀'], ['소년'], ['조약돌'], ['소년'], ['조약돌'], ['소녀'], ['소녀'], ['소년'], ['주머니'], ['조약돌'], ['버릇'], ['소년'], ['소년'], ['놀라'], ['소년'], ['달리기'], ['디딤돌'], ['메밀'], ['액체'], ['코피'], ['소년'], ['코피'], ['바보'], ['바보'], ['소녀'], ['여태'], ['조개'], ['소녀'], ['소녀'], ['비단'], ['조개'], ['이름'], ['소녀'], ['소년'], ['가야'], ['너머'], ['우리'], ['서울'], ['소풍'], ['소녀'], ['바보'], ['바보'], ['허수아비'], ['참새'], ['참새'], ['허수아비'], ['허수아비'], ['소녀'], ['보조개'], ['허수아비'], ['소년'], ['집안일'], ['소녀'], ['메뚜기'], ['소년'], ['독수리'], ['독수리'], ['독수리'], ['돌고'], ['소녀'], ['허수아비'], ['허수아비'], ['도랑'], ['원두막'], ['참외'], ['참외'], ['수박'], ['하나'], ['참외'], ['그루'], ['물어'], ['손톱'], ['소녀'], ['산이'], ['단풍'], ['들국화'], ['싸리'], ['도라지'], ['도라지'], ['양산'], ['마타리'], ['소녀'], ['마타리'], ['양산'], ['보조개'], ['소년'], ['소녀'], ['하나'], ['골짜기'], ['말라가'], ['서울'], ['놀라'], ['소년'], ['제가'], ['소녀'], ['소년'], ['소년'], ['이거'], ['송진'], ['송아지'

In [64]:
model = word2vec.Word2Vec(sents, size=200,window=100,hs=1,min_count=1,sg=1)
# size:벡터차원, window:현재단어와 예측단어 최대거리, hs=(softmax=1), min_count=최소 빈도
# sg=(skip-gram=1, CBOW=otherwise)


print(list(model.wv.vocab.keys()))
print("vocab length : %d"%len(model.wv.vocab))

['소나기', '황순원', '소년', '시네', '소녀', '서울', '돌아오는길', '분홍', '스웨터', '고기', '조약돌', '바보', '천한', '주머니', '버릇', '놀라', '달리기', '디딤돌', '메밀', '액체', '코피', '여태', '조개', '비단', '이름', '가야', '너머', '우리', '소풍', '허수아비', '참새', '보조개', '집안일', '메뚜기', '독수리', '돌고', '도랑', '원두막', '참외', '수박', '하나', '그루', '물어', '손톱', '산이', '단풍', '들국화', '싸리', '도라지', '양산', '마타리', '골짜기', '말라가', '제가', '이거', '송진', '송아지', '바투', '남색', '안고', '예서', '농부', '상하면', '구름', '장이', '사면', '떡갈나무', '빗방울', '기둥', '지붕', '무명', '저고리', '고온', '송이', '곳도', '수수', '라다', '돌리지', '햇빛', '보니', '불어', '달려와', '인제', '하도', '진흙', '사해', '초시', '손자', '그런지', '단맛', '호두', '내리', '그늘', '근동', '이만', '하면', '망태기', '서당', '수탉', '허허', '실속', '쇠파리', '양평읍', '보나', '아니야', '대대로', '바느질', '복이', '기전']
vocab length : 109


In [65]:
wv = model.wv #Word2Vec model
del(model)
# 전달받은 sigwords 중 model에 포함된 단어를 우선순위 순서로 추려냄
sigvocs = []
missvocs = []
hit = 0
miss = 0
for worddic in tfidf_dict:
    try:
        word = worddic
        if wv.vocab[word]:
            sigvocs.append(word)
            hit += 1
        if hit >= length:
            break
    except:
        missvocs.append(word)
        miss += 1
# 디버깅용. 추후 삭제.
print("missed: %d"  % miss)
for voc in missvocs:
    print(voc)


# 디스턴스 매트릭스를 데이터프레임 형태로 만듦
distDF =  pandas.DataFrame(columns = sigvocs , index = sigvocs)
for i in sigvocs:
    dists = []
    for j in sigvocs:
        dist = round(wv.distance(i, j), 6)
        dists.append(0 if dist < 1.0e-2 else dist)
    distDF[i] = dists
print(distDF)

missed: 5
바보
소녀
소년
조약돌
허수아비
            바보        소녀        소년       조약돌      허수아비
바보    0.000000  0.844495  0.992123  1.041638  0.990084
소녀    0.844495  0.000000  1.035645  1.068918  0.948478
소년    0.992123  1.035645  0.000000  0.991478  1.013368
조약돌   1.041638  1.068918  0.991478  0.000000  1.110616
허수아비  0.990084  0.948478  1.013368  1.110616  0.000000


In [66]:
for i in sigvocs:
    print(i)
    print(wv.most_similar(positive=i, negative=[]))

바보
[('메밀', 0.23729155957698822), ('마타리', 0.18524201214313507), ('소녀', 0.15550512075424194), ('황순원', 0.13361135125160217), ('사해', 0.12627114355564117), ('떡갈나무', 0.1255096048116684), ('여태', 0.11644387990236282), ('서울', 0.11018574237823486), ('그늘', 0.10755077004432678), ('안고', 0.0874883383512497)]
소녀
[('바보', 0.15550513565540314), ('곳도', 0.1120748221874237), ('디딤돌', 0.10593970865011215), ('비단', 0.10072492063045502), ('싸리', 0.09081161022186279), ('양산', 0.09026648104190826), ('우리', 0.08774781972169876), ('골짜기', 0.08591955900192261), ('여태', 0.08170177042484283), ('고온', 0.08132626116275787)]
소년
[('고온', 0.28634577989578247), ('망태기', 0.12995381653308868), ('실속', 0.11634930968284607), ('기둥', 0.11332067847251892), ('사면', 0.10881637036800385), ('지붕', 0.10276883840560913), ('우리', 0.09189164638519287), ('하도', 0.09135960042476654), ('떡갈나무', 0.09124300628900528), ('남색', 0.08807358145713806)]
조약돌
[('망태기', 0.13999345898628235), ('코피', 0.13963933289051056), ('하도', 0.13753701746463776), ('아니야', 0.136609852

In [67]:
search=[]
for i in sigvocs:
    for j in distDF[i].sort_values().index[1:3]:
           search.append([i,j])

In [69]:
for i in search:
#     i = str(i)
#     i = i.replace("(","").replace(")","").replace("'","").replace(" ","").split(",")
    print((i))
    print(wv.most_similar(positive=i, negative=[]))

['바보', '소녀']
[('마타리', 0.16782164573669434), ('메밀', 0.1504785716533661), ('여태', 0.1303417682647705), ('사해', 0.11234699189662933), ('곳도', 0.10346396267414093), ('떡갈나무', 0.10302431881427765), ('서울', 0.08120134472846985), ('남색', 0.08060164749622345), ('그루', 0.07949734479188919), ('디딤돌', 0.07390785962343216)]
['바보', '허수아비']
[('그늘', 0.19530512392520905), ('마타리', 0.14958007633686066), ('메밀', 0.14917729794979095), ('소녀', 0.14566963911056519), ('집안일', 0.14109638333320618), ('여태', 0.1279769390821457), ('황순원', 0.12291322648525238), ('도라지', 0.11341261863708496), ('서울', 0.10167548060417175), ('햇빛', 0.0899549275636673)]
['소녀', '바보']
[('마타리', 0.16782164573669434), ('메밀', 0.1504785716533661), ('여태', 0.1303417682647705), ('사해', 0.11234699189662933), ('곳도', 0.10346396267414093), ('떡갈나무', 0.10302431881427765), ('서울', 0.08120134472846985), ('남색', 0.08060164749622345), ('그루', 0.07949734479188919), ('디딤돌', 0.07390785962343216)]
['소녀', '허수아비']
[('싸리', 0.1294887512922287), ('골짜기', 0.12360583245754242), ('바보',

In [26]:
############################################

In [24]:
################################

In [33]:
import pandas as pd
pd.options.mode.chained_assignment = None

import numpy as np
np.random.seed(0)

from konlpy.tag import Okt
twitter = Okt()

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from sklearn.feature_extraction.text import HashingVectorizer

In [34]:
def tokenizer(raw, pos=["Noun","Alpha","Verb","Number"], stopword=[]):
    return [
        word for word, tag in twitter.pos(
            raw, 
            norm=True,   # normalize 그랰ㅋㅋ -> 그래ㅋㅋ
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

In [35]:

file = open('./TheLittlePrince.txt','r',encoding='utf-8')
raw_lines = file.readlines()

# 2. 변수 rawdata 저장
rawdata = []
for line in raw_lines:
#     line= "\n".join([s for s in stuff.split("\n") if s])
    rawdata.append(line)

In [36]:
print(rawdata)

['\ufeff여섯 살 적에 나는 "체험한 이야기"라는 제목의, 원시림에 관한 책에서 기막힌 그림 하나를 본 적이 있다. 맹수를 집어삼키고 있는 보아 구렁이 그림이었다. 위의 그림은 그것을 옮겨 그린 것이다.\n', ' 그 책에는 이렇게 씌어 있었다.\n', ' "보아 구렁이는 먹이를 씹지도 않고 통째로 집어삼킨다.그리고는 꼼짝도 하지 못하고 여섯 달 동안 잠을 자면서 그것을 소화시킨다."\n', ' 나는 그래서 밀림 속에서의 모험에 대해 한참 생각해 보고 난 끝에 색연필을 가지고 내 나름대로 내 생애 첫번째 그림을 그려보았다. 나의 그림 제 1호였다. 그것은 이런 그림이었다.\n', ' 나는 그 걸작품을 어른들에게 보여 주면서내 그림이 무섭지 않느냐고 물었다.\n', ' 그들은 "모자가 뭐가 무섭다는 거니?" 하고 대답했다.\n', ' 내 그림은 모자를 그린 게 아니었다. 그것은 코끼리를 소화시키고 있는 보아 구렁이었다.\n', ' 그래서 나는 어른들이 알아볼 수 있도록 보아 구렁이의 속을 그렸다. 어른들은 언제나 설명을 해주어야만 한다. 나의 그림 제 2호는 이러했다.\n', ' 어른들은 속이 보이거나 보이지 않거나 하는 보아 구렁이의 그림들은 집어치우고 차라리 지리, 역사, 계산, 그리고 문법 쪽에 관심을 가져보는 게 좋을 것이라고 충고해 주었다.\n', ' 그래서 나는 여섯 살 적에 화가라는 멋진 직업을 포기해 버렸다.내 그림제 1호와 제 2호가 성공을 거두지 못한 데 낙심해 버렸던 것이다. 어른들은언제나 스스로는 아무것도 이해하지 못한다.자꾸자꾸 설명을 해주어야 하니 맥빠지는 노릇이 아닐 수 없다.\n', ' 그래서 다른 직업을 선택하지 않을 수 없게 된 나는 비행기 조종하는 법을배웠다.세계의 여기저기 거의 안 가본 데 없이 나는 날아다녔다.그러니지리는 정말로 많은 도움을 준 셈이었다.한번 슬쩍 보고도 중국과 애리조나를 나는 구별할 수 있었던 것이다.그것은 밤에 길을 잃었을 때 아주 유용한 일이다.\n', ' 나는 그리하여 일생 동안 수없이 많은 점잖

In [37]:
vectorize = HashingVectorizer(
    tokenizer=tokenizer,
    n_features=7               # 기본 feature 수를 설정하며 기본값이 2의 20승이다. 아래 예시를 위해 feature 를 7로 한정했으나, 아래 유사문장을 찾을때는 다시 n_features 주석처리 했다.
)
X = vectorize.fit_transform(rawdata)
 
print(X.shape)
 
print(X.toarray())

(977, 7)
[[-0.26726124 -0.26726124  0.26726124 ...  0.         -0.26726124
   0.80178373]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.37796447 -0.75592895  0.         ...  0.          0.
   0.37796447]
 ...
 [ 0.51639778  0.51639778  0.         ... -0.25819889 -0.25819889
  -0.51639778]
 [-0.12216944  0.85518611  0.24433889 ...  0.24433889 -0.24433889
   0.12216944]
 [ 0.          0.52075564  0.13018891 ... -0.52075564 -0.13018891
  -0.39056673]]


In [42]:

# search 문장 벡터
srch_vector = vectorize.transform([
    '화산'
])
 
print(srch_vector.shape)
# (1, 7)


(1, 7)


In [43]:
from sklearn.metrics.pairwise import linear_kernel
 
# linear_kernel는 두 벡터의 dot product 이다.
cosine_similar = linear_kernel(srch_vector, X).flatten()
# cosine_similar = (srch_vector*X.T).toarray().flatten()
 
print(cosine_similar)
# [0.         0.         0.62017367 0.31622777 0.3]
 
print(cosine_similar.shape)
# (5,)
 

[ 0.          0.          0.          0.          0.          0.
  0.5         0.         -0.3592106   0.12309149  0.         -0.28867513
 -0.51604685 -0.40824829  0.          0.21821789  0.          0.
  0.          0.          0.          0.          0.          0.
 -0.28867513 -0.57735027 -0.75592895  0.          0.          0.16439899
  0.70710678  0.5         0.          0.         -0.5        -0.57735027
  0.          0.          0.         -0.70710678  0.31622777  0.
  0.          1.          1.         -0.40824829  0.          0.
  0.         -0.47140452  0.          0.          0.         -0.57735027
  0.          0.          0.          0.63245553  0.          0.
  0.          0.          0.          0.          0.30151134 -0.57735027
  0.         -0.81649658 -0.5         0.66666667  0.57735027  0.40824829
 -0.57735027  0.          0.          0.          1.          0.5
  0.          0.         -0.64051262  0.          0.35355339  0.2236068
  0.1796053   0.53452248 -0.377964

In [44]:

# 유사한 rawdata index
sim_rank_idx = cosine_similar.argsort()[::-1]
print(sim_rank_idx)
#[2 3 4 1 0]
 

[175  76 472 841  44 112  43 567 152 972 502 201 890 189 181 482 366 718
 362 360 908 352 270 549 484 504 512  30 507 501 481 818  69 643 897  57
 287 211 345 340 364 132 658 765 711 485 476 478  70  85 125 247 174 871
 518 560   6  77 475 937  31 907 804 180 384 615 350 193 561 795 576 219
 115 499 812 535  71 923 130 666 250 225  89 806 305 809 862 346 623 403
 798 903 426 408 613 465 116 261 514 110  82 892 449 726 592 406 101 854
 284  40 859  64 208 675 432 786 232 111 975 195  83  15 229 716 962 170
 819  84  29 970 265 900   9 490 240 489 494 113 493 483 487 216 215 114
 239 470 480 479 119 120 122 456 123 454 453 124 251 450 252 448 126 445
 444 118 461 462 212 243 244 477 245 246 213 471 463 238 469 468 467 466
 464 495 233 497 546 552 551 550 227  97 547 545 538 100 543 542 541 540
 218 553 554 555  95 557 559 562 563 564 566 568 569  88 571 224 573 574
 539 537 498 509 513 217 231 109 510 442 508 536 506 234 235 236 237 500
 515 107 517 519 106 105 522 523 524 525 526 527 10

In [45]:
for i in sim_rank_idx:
    if cosine_similar[i] > 0:
        print('{} / score : {}'.format(rawdata[i], cosine_similar[i]))

 "참 아름다우시군요!"
 / score : 1.0
 "괜찮아. 내가 사는 곳은 아주 작으니까!"
 / score : 1.0
 "지리학자가 뭐에요?"
 / score : 1.0
 그러자 나는 그가 무엇을 찾고 있었는지를 깨달았다.
 / score : 1.0
 "거기 있는 걸로 아마 충분할 거다. 네게 준 건 아주 작은 양이니까."
 / score : 1.0
 "그건 기율(紀律)의 문제야."
 / score : 1.0
 "내가 사는 곳은 아주 작거든......"
 / score : 1.0
 "난 배보다 더 먼 곳으로 너를 데려다줄 수 있어."
 / score : 1.0
 그는 깜짝 놀라서 나를 바라보았다.
 / score : 0.9486832980505138
 어느 때는 (한두 번 방심할 수도 있지. 그러면 끝장인데!어느날 밤 그가유리덮개를 잊었거나 양이 밤중에 소리없이 밖으로 나왔을지도 몰라......)하는 생각이 들기도 한다. 그러면 작은 방울들은 모두 눈물방울로 변한다!......
 / score : 0.944911182523068
 "아, 내 별은 별로 흥미로울 게 없어요. 아주 작거든요. 화산이 셋있어요. 둘은 불이 있는 화산이고 하나는 불이 꺼진 화산이지요. 하지만 언제 어떻 게 될지 모르지요."
 / score : 0.8320502943378437
 나는 어린 왕자가 철새들의 이동을 이용하여 별을 떠나왔으리라 생각한다.떠나는날 아침 그는 그의 별을 잘 정돈해 놓았다. 불을 뿜는 화산들은 정성스레 쑤셔서 청소했다. 그에게는 불을 뿜는 화산이 둘 있었다. 그런데 그것은 아침밥을 데우는 데 아주 편리했다. 불이 꺼져 있는 화산도 하나 있었다그러나 그의 말처럼"어떻게 될지 알 수 없는 일이었다."그는 그래서 불꺼진 화산도 잘 쑤셔 놓았다.화산들은 잘 청소되어있을 때는 부드럽게,규칙적으로, 폭발하지 않고 타오른다. 화산의 폭발은 벽난로의 불과 마찬가지인 것이다. 물론 우리 지구 위에서는 우리들의 화산을 쑤시기에는 우리가너무 작다. 그래서 화산이 우리에게 숱한