In [1]:
from collections import Counter
from konlpy.tag import Kkma
from konlpy.utils import pprint
from konlpy.tag import Twitter
from konlpy.tag import Komoran
from gensim.models import Word2Vec
import matplotlib.pyplot as plt
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

In [32]:
import re

#파일 읽어오기
file = open('./TheLittlePrince.txt','r',encoding='utf-8')
line = file.read()

#장(chapter)마다 나눔
sentences = re.split('(?<=[2-9]\n)|(?<=[0-9][0-9]\n)|(?<=[0-9][0-9][0-9]\n)', line)

#Komoran 형태소 분석을 위한 전처리
sent=[]
for stuff in sentences:
#         stuff = stuff.replace("'","").replace("?","").replace(".","").replace("'","").replace('"'
# ,"").replace("!","").replace("-","").replace('"',"").replace("\n","")
#         stuff = re.sub("\n","", line).strip()
        sent.append(stuff)

In [33]:
# twitter = Komoran(userdic='./user_dic.txt')
twitter = Twitter()

c:\users\sun\appdata\local\programs\python\python37\lib\site-packages\konlpy\tag\_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


In [34]:
#형태소분석
sentences_tag = []
for sentence in sent:
    morph = twitter.pos(sentence)
    sentences_tag.append(morph)

In [35]:
#명사 추출
noun_adj=[]

#komoran
# for sentence1 in sentences_tag:
#     for word, tag in sentence1:
#         if tag in ['NNP']: 
#             noun_adj.append(word)

#twitter
for sentence1 in sentences_tag:
    for word, tag in sentence1:
        if len(word)>1:
            if tag in ['Noun']: #komoran
                noun_adj.append(word)

In [36]:
print(noun_adj)

['여섯', '체험', '이야기', '제목', '원시림', '그림', '하나', '맹수', '보아', '구렁이', '그림', '그것', '그린', '씌어', '보아', '구렁이', '먹이', '통째', '꼼짝', '여섯', '동안', '그것', '소화', '밀림', '모험', '대해', '한참', '생각', '보고', '색연필', '가지', '나름', '생애', '그림', '그림', '그것', '작품', '어른', '그림', '모자', '대답', '그림', '모자', '그린', '그것', '코끼리', '소화', '보아', '구렁', '어른', '보아', '구렁이', '어른', '설명', '그림', '어른', '보이지', '보아', '구렁이', '그림', '차라리', '지리', '역사', '계산', '문법', '관심', '충고', '여섯', '화가', '직업', '포기', '그림', '호가', '성공', '낙심', '어른', '스스로', '이해', '설명', '하니', '노릇', '다른', '직업', '선택', '비행기', '조종', '세계', '여기저기', '거의', '도움', '한번', '보고', '중국', '애리조나', '구별', '그것', '아주', '일이', '일생', '동안', '사람', '접촉', '어른', '가까이', '대한', '생각', '조금', '사람', '만날', '간직', '예의', '그림', '가지', '사람', '시험', '보고', '사람', '이해', '사람', '으례', '사람', '모자', '대답', '보아', '구렁이', '원시림', '이야기', '이해', '이야기', '브리지', '골프', '정치', '넥타이', '대해', '이야기', '어른', '매우', '청년', '몹시', '여섯', '사하라', '사막', '비행기', '고장', '마음', '진정', '이야기', '상대', '홀로', '비행기', '모터', '군데', '기사도', '승객', '혼자', '수선', '시도', '채비', '그것', '문제', '이렛날', '동안

In [37]:
############# TF-IDF###################

In [38]:
import pandas as pd
from collections import Counter
from sklearn.manifold import TSNE
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
vector = CountVectorizer()
print(vector.fit_transform(noun_adj).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
{'여섯': 722, '체험': 1019, '이야기': 822, '제목': 927, '원시림': 783, '그림': 123, '하나': 1084, '맹수': 339, '보아': 480, '구렁이': 92, '그것': 114, '그린': 121, '씌어': 663, '먹이': 345, '통째': 1048, '꼼짝': 165, '동안': 274, '소화': 600, '밀림': 419, '모험': 371, '대해': 253, '한참': 1102, '생각': 567, '보고': 477, '색연필': 565, '가지': 15, '나름': 177, '생애': 569, '작품': 873, '어른': 703, '모자': 368, '대답': 243, '코끼리': 1040, '구렁': 91, '설명': 581, '보이지': 482, '차라리': 993, '지리': 976, '역사': 727, '계산': 62, '문법': 400, '관심': 82, '충고': 1032, '화가': 1138, '직업': 983, '포기': 1066, '호가': 1126, '성공': 583, '낙심': 185, '스스로': 624, '이해': 832, '하니': 1088, '노릇': 202, '다른': 220, '선택': 580, '비행기': 520, '조종': 941, '세계': 588, '여기저기': 717, '거의': 41, '도움': 268, '한번': 1097, '중국': 963, '애리조나': 689, '구별': 95, '아주': 676, '일이': 850, '일생': 846, '사람': 531, '접촉': 914, '가까이': 1, '대한': 251, '조금': 936, '만날': 321, '간직': 22, '예의': 738, '시험': 642, '으례': 795, '브리지':

In [40]:
tfidfv = TfidfVectorizer().fit(noun_adj)
print(tfidfv.transform(noun_adj).toarray())
print(tfidfv.vocabulary_)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
{'여섯': 722, '체험': 1019, '이야기': 822, '제목': 927, '원시림': 783, '그림': 123, '하나': 1084, '맹수': 339, '보아': 480, '구렁이': 92, '그것': 114, '그린': 121, '씌어': 663, '먹이': 345, '통째': 1048, '꼼짝': 165, '동안': 274, '소화': 600, '밀림': 419, '모험': 371, '대해': 253, '한참': 1102, '생각': 567, '보고': 477, '색연필': 565, '가지': 15, '나름': 177, '생애': 569, '작품': 873, '어른': 703, '모자': 368, '대답': 243, '코끼리': 1040, '구렁': 91, '설명': 581, '보이지': 482, '차라리': 993, '지리': 976, '역사': 727, '계산': 62, '문법': 400, '관심': 82, '충고': 1032, '화가': 1138, '직업': 983, '포기': 1066, '호가': 1126, '성공': 583, '낙심': 185, '스스로': 624, '이해': 832, '하니': 1088, '노릇': 202, '다른': 220, '선택': 580, '비행기': 520, '조종': 941, '세계': 588, '여기저기': 717, '거의': 41, '도움': 268, '한번': 1097, '중국': 963, '애리조나': 689, '구별': 95, '아주': 676, '일이': 850, '일생': 846, '사람': 531, '접촉': 914, '가까이': 1, '대한': 251, '조금': 936, '만날': 321, '간직': 22, '예의

In [54]:
# TF-IDF 설정
tfidf = TfidfVectorizer(max_features = 15, max_df=0.95, min_df=0) #(max_features = 5) <- 상위 5개만 추출

#generate tf-idf term-document matrix
A_tfidf_sp = tfidf.fit_transform(noun_adj)

In [55]:
tfidf_dict = tfidf.get_feature_names()
print(tfidf_dict)

['가로등', '가지', '거지', '그것', '그림', '다른', '다시', '대답', '때문', '사람', '생각', '아저씨', '아주', '여우', '왕자']


In [56]:
print(tfidf)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=0.95, max_features=15,
                min_df=0, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)


In [57]:
#############Word2Vec######################

In [58]:
sents = [doc.split(" ") for doc in noun_adj] #Word2Vec 을 위한 전처리

In [59]:
from gensim.models import word2vec

model = word2vec.Word2Vec(sents, size=200,window=10,hs=1,min_count=2,sg=1)

print(list(model.wv.vocab.keys()))
print("vocab length : %d"%len(model.wv.vocab))

print(model.wv.most_similar("형식"))

['여섯', '이야기', '원시림', '그림', '하나', '보아', '구렁이', '그것', '그린', '꼼짝', '동안', '소화', '대해', '한참', '생각', '보고', '가지', '작품', '어른', '모자', '대답', '코끼리', '설명', '보이지', '지리', '역사', '계산', '문법', '화가', '직업', '포기', '낙심', '스스로', '이해', '하니', '노릇', '다른', '비행기', '세계', '거의', '도움', '한번', '중국', '구별', '아주', '일이', '사람', '가까이', '대한', '조금', '만날', '매우', '몹시', '사하라', '사막', '고장', '마음', '모터', '군데', '승객', '혼자', '채비', '문제', '수천', '마일', '한가운데', '무렵', '목소리', '얼마나', '여러분', '상상', '마리', '기겁', '조그만', '얼굴', '훗날', '가장', '여기', '매력', '잘못', '때문', '이외', '사실', '피곤', '목마름', '구석', '정신', '듯이', '다시', '되풀이', '부탁', '신비', '누구', '거기', '마련', '죽음', '위험', '마주', '포켓', '종이', '소년', '그릴', '기분', '양은', '위해', '주의', '벌써', '친구', '모습', '미소', '이건', '마찬가지', '이상', '상자', '심판', '바로', '주어', '아마', '고개', '그다지', '지도', '왕자', '질문', '모든', '처음', '물건', '도대체', '아저씨', '하늘', '그거', '까르르', '문득', '존재', '로움', '줄기', '갑자기', '멀리', '오지', '보물', '비밀', '짐작', '하리', '어디', '아무', '수도', '웃음', '곧장', '가도', '수가', '지구', '이름', '떠돌이별', '망원경', '정도', '천문학자', '발견', '대신', '번호', '혹성', '터키', '자신', '증명'

KeyError: "word '형식' not in vocabulary"

In [ ]:
from gensim.models import Word2Vec
import pandas

In [60]:
wv = model.wv #Word2Vec model
# del(model)
# 전달받은 sigwords 중 model에 포함된 단어를 우선순위 순서로 추려냄
sigvocs = []
missvocs = []
hit = 0
miss = 0
for worddic in tfidf_dict:
    try:
        word = worddic
        if wv.vocab[word]:
            sigvocs.append(word)
            hit += 1
        if hit >= length:
            break
    except:
        missvocs.append(word)
        miss += 1
# 디버깅용. 추후 삭제.
print("missed: %d"  % miss)
for voc in missvocs:
    print(voc)


# 디스턴스 매트릭스를 데이터프레임 형태로 만듦
distDF =  pandas.DataFrame(columns = sigvocs , index = sigvocs)
for i in sigvocs:
    dists = []
    for j in sigvocs:
        dist = round(wv.distance(i, j), 6)
        dists.append(0 if dist < 1.0e-2 else dist)
    distDF[i] = dists
print(distDF)

missed: 15
가로등
가지
거지
그것
그림
다른
다시
대답
때문
사람
생각
아저씨
아주
여우
왕자
          가로등        가지        거지        그것        그림        다른        다시  \
가로등  0.000000  0.885106  0.974398  1.020526  1.079557  1.083609  1.031271   
가지   0.885106  0.000000  1.010008  1.013926  1.033998  0.922781  1.001057   
거지   0.974398  1.010008  0.000000  1.136068  1.005687  0.899622  1.048628   
그것   1.020526  1.013926  1.136068  0.000000  1.078999  1.107461  1.028212   
그림   1.079557  1.033998  1.005687  1.078999  0.000000  0.956404  1.029121   
다른   1.083609  0.922781  0.899622  1.107461  0.956404  0.000000  1.051873   
다시   1.031271  1.001057  1.048628  1.028212  1.029121  1.051873  0.000000   
대답   0.926561  0.979757  0.943967  0.961573  0.959602  1.019652  0.991341   
때문   0.979635  1.024832  1.091364  0.970210  1.051432  0.974933  0.980898   
사람   1.058978  1.074508  1.049646  0.974800  0.909363  0.998857  0.858192   
생각   1.052073  0.970867  1.024591  0.895585  1.017764  0.901581  1.044605   
아저씨  0.862673  0.9

In [49]:
print(distDF)

          그것        다시        사람        생각        왕자
그것  0.000000  1.028212  0.974800  0.895585  0.899601
다시  1.028212  0.000000  0.858192  1.044605  1.024303
사람  0.974800  0.858192  0.000000  0.889188  1.062544
생각  0.895585  1.044605  0.889188  0.000000  0.944452
왕자  0.899601  1.024303  1.062544  0.944452  0.000000


In [ ]:
print(model.words_nearest('영채 형식'.split()))

In [50]:
print(model.most_similar(positive=['왕자','생각'], negative=['사람']))

[('거기', 0.24357470870018005), ('순간', 0.19823065400123596), ('뿜는', 0.17031969130039215), ('자기', 0.16283488273620605), ('때문', 0.15963438153266907), ('동안', 0.15398666262626648), ('눈물', 0.15326553583145142), ('풀숲', 0.1522294580936432), ('통해', 0.1514396071434021), ('만날', 0.1450711488723755)]


c:\users\sun\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


In [ ]:
############################################

In [ ]:
import pandas as pd
pd.options.mode.chained_assignment = None

import numpy as np
np.random.seed(0)

from konlpy.tag import Twitter
twitter = Twitter()

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from sklearn.feature_extraction.text import HashingVectorizer

In [ ]:
def tokenizer(raw, pos=["Noun","Alpha","Verb","Number"], stopword=[]):
    return [
        word for word, tag in twitter.pos(
            raw, 
            norm=True,   # normalize 그랰ㅋㅋ -> 그래ㅋㅋ
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

In [ ]:

file = open('./mujung.txt','r',encoding='utf-8')
raw_lines = file.readlines()

# 2. 변수 rawdata 저장
rawdata = []
for line in raw_lines:
    rawdata.append(line)

In [ ]:
print(rawdata)

In [ ]:
vectorize = HashingVectorizer(
    tokenizer=tokenizer,
    n_features=7               # 기본 feature 수를 설정하며 기본값이 2의 20승이다. 아래 예시를 위해 feature 를 7로 한정했으나, 아래 유사문장을 찾을때는 다시 n_features 주석처리 했다.
)
X = vectorize.fit_transform(rawdata)
 
print(X.shape)
 
print(X.toarray())

In [ ]:

# search 문장 벡터
srch_vector = vectorize.transform([
    '영채 형식'
])
 
print(srch_vector.shape)
# (1, 7)


In [ ]:
from sklearn.metrics.pairwise import linear_kernel
 
# linear_kernel는 두 벡터의 dot product 이다.
cosine_similar = linear_kernel(srch_vector, X).flatten()
# cosine_similar = (srch_vector*X.T).toarray().flatten()
 
print(cosine_similar)
# [0.         0.         0.62017367 0.31622777 0.3]
 
print(cosine_similar.shape)
# (5,)
 
# 유사한 rawdata index
sim_rank_idx = cosine_similar.argsort()[::-1]
print(sim_rank_idx)
#[2 3 4 1 0]
 
for i in sim_rank_idx:
    if cosine_similar[i] > 0:
        print('{} / score : {}'.format(rawdata[i], cosine_similar[i]))

In [66]:
###################################연관분석

In [67]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [68]:
import numpy as np
import pandas as pd
from apyori import apriori

In [56]:
association_rules = apriori(sentences_tag,min_support=0.0053, min_confidence=0.20, min_lift=3, min_length=2)