In [79]:
from collections import Counter
from konlpy.tag import Kkma
from konlpy.utils import pprint
from konlpy.tag import Twitter
from konlpy.tag import Komoran
from gensim.models import Word2Vec
import matplotlib.pyplot as plt
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

In [119]:
import re

#파일 읽어오기
file = open('./mujung.txt','r',encoding='utf-8')
line = file.read()

#장(chapter)마다 나눔
sentences = re.split('(?<=[2-9]\n)|(?<=[0-9][0-9]\n)|(?<=[0-9][0-9][0-9]\n)', line)

#Komoran 형태소 분석을 위한 전처리
sent=[]
for stuff in sentences:
#         stuff = stuff.replace("'","").replace("?","").replace(".","").replace("'","").replace('"'
# ,"").replace("!","").replace("-","").replace('"',"").replace("\n","")
#         stuff = re.sub("\n","", line).strip()
        sent.append(stuff)

In [120]:
# twitter = Komoran(userdic='./user_dic.txt')
twitter = Twitter()

c:\users\sun\appdata\local\programs\python\python37\lib\site-packages\konlpy\tag\_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


In [121]:
#형태소분석
sentences_tag = []
for sentence in sent:
    morph = twitter.pos(sentence)
    sentences_tag.append(morph)

In [122]:
#명사 추출
noun_adj=[]

#komoran
# for sentence1 in sentences_tag:
#     for word, tag in sentence1:
#         if tag in ['NNP']: 
#             noun_adj.append(word)

#twitter
for sentence1 in sentences_tag:
    for word, tag in sentence1:
        if len(word)>1:
            if tag in ['Noun']: #komoran
                noun_adj.append(word)

In [123]:
print(noun_adj)

['이광수', '무정', '경성', '학교', '영어', '교사', '이형식', '오후', '두시', '영어', '시간', '마치', '유월', '안동', '장로', '간다', '장로', '선형', '명년', '미국', '유학', '가기', '영어', '준비', '차로', '이형식', '매일', '시간', '가정교사', '빙하', '오늘', '오후', '세시', '수업', '시작', '이형식', '독신', '여자', '가까이', '교제', '청년', '모양', '여자', '대하', '자연', '생각', '얼굴', '고개', '저절로', '남자', '여자', '핑계', '어서', '가까이', '한마디', '사람', '형식', '여러', '가지', '생각', '우선', '처음', '인사', '남자', '남자', '모양', '처음', '이형식', '잠시', '자라', '무슨', '차별', '저편', '먼저', '인사', '인사', '그것', '교수', '방법', '어제', '장로', '청탁', '지금껏', '생각', '건마는', '무슨', '묘방', '가운데', '책상', '하나', '거기', '마주', '입김', '입김', '서로', '저편', '사시', '가미', '양갈래', '머릿단', '이마', '책상', '아래', '무릎', '무릎', '마주', '하렷다', '생각', '형식', '얼굴', '혼자', '빙긋', '만일', '마음', '어찌', '대로', '책상', '멀리', '만일', '저편', '무릎', '깜짝', '무릎', '무슨', '냄새', '여자', '대하', '실례', '점심', '담배', '입김', '불어', '입김', '손바닥', '반사', '코로', '냄새', '유무', '시험', '형식', '아뿔싸', '어찌하여', '생각', '마음', '주먹', '불끈', '전신', '주어', '생각', '하나', '가슴속', '불길', '일어난다', '미스터', '어디', '소리', '깜짝', '고개', '동류', '신우선', '대팻밥', '모자', 

In [124]:
############# TF-IDF###################

In [125]:
import pandas as pd
from collections import Counter
from sklearn.manifold import TSNE
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [126]:
vector = CountVectorizer()
print(vector.fit_transform(noun_adj).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
{'이광수': 3022, '무정': 1361, '경성': 215, '학교': 4155, '영어': 2714, '교사': 363, '이형식': 3103, '오후': 2775, '두시': 1033, '시간': 2283, '마치': 1170, '유월': 2944, '안동': 2473, '장로': 3310, '간다': 61, '선형': 2068, '명년': 1261, '미국': 1411, '유학': 2951, '가기': 2, '준비': 3606, '차로': 3734, '매일': 1224, '가정교사': 47, '빙하': 1840, '오늘': 2740, '세시': 2116, '수업': 2218, '시작': 2311, '독신': 968, '여자': 2652, '가까이': 3, '교제': 375, '청년': 3831, '모양': 1301, '대하': 905, '자연': 3254, '생각': 2004, '얼굴': 2601, '고개': 252, '저절로': 3362, '남자': 677, '핑계': 4116, '어서': 2569, '한마디': 4174, '사람': 1870, '형식': 4288, '여러': 2634, '가지': 52, '우선': 2853, '처음': 3788, '인사': 3123, '잠시': 3286, '자라': 3235, '무슨': 1356, '차별': 3736, '저편': 3365, '먼저': 1245, '그것': 471, '교수': 365, '방법': 1525, '어제': 2574, '청탁': 3843, '지금껏': 3644, '건마는': 169, '묘방': 1332, '가운데': 41, '책상': 3779, '하나': 4117, '거기': 140, '마주': 1166, '입김': 3209, '서로': 2025, '사시': 1893, '가미': 

In [127]:
tfidfv = TfidfVectorizer().fit(noun_adj)
print(tfidfv.transform(noun_adj).toarray())
print(tfidfv.vocabulary_)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
{'이광수': 3022, '무정': 1361, '경성': 215, '학교': 4155, '영어': 2714, '교사': 363, '이형식': 3103, '오후': 2775, '두시': 1033, '시간': 2283, '마치': 1170, '유월': 2944, '안동': 2473, '장로': 3310, '간다': 61, '선형': 2068, '명년': 1261, '미국': 1411, '유학': 2951, '가기': 2, '준비': 3606, '차로': 3734, '매일': 1224, '가정교사': 47, '빙하': 1840, '오늘': 2740, '세시': 2116, '수업': 2218, '시작': 2311, '독신': 968, '여자': 2652, '가까이': 3, '교제': 375, '청년': 3831, '모양': 1301, '대하': 905, '자연': 3254, '생각': 2004, '얼굴': 2601, '고개': 252, '저절로': 3362, '남자': 677, '핑계': 4116, '어서': 2569, '한마디': 4174, '사람': 1870, '형식': 4288, '여러': 2634, '가지': 52, '우선': 2853, '처음': 3788, '인사': 3123, '잠시': 3286, '자라': 3235, '무슨': 1356, '차별': 3736, '저편': 3365, '먼저': 1245, '그것': 471, '교수': 365, '방법': 1525, '어제': 2574, '청탁': 3843, '지금껏': 3644, '건마는': 169, '묘방': 1332, '가운데': 41, '책상': 3779, '하나': 4117, '거기': 140, '마주': 1166, '입김': 

In [143]:
# TF-IDF 설정
tfidf = TfidfVectorizer(max_features = 5, max_df=0.95, min_df=0) #(max_features = 5) <- 상위 5개만 추출

#generate tf-idf term-document matrix
A_tfidf_sp = tfidf.fit_transform(noun_adj)

In [144]:
tfidf_dict = tfidf.get_feature_names()
print(tfidf_dict)

['사람', '생각', '영채', '자기', '형식']


In [130]:
#############Word2Vec######################

In [131]:
sents = [doc.split(" ") for doc in noun_adj] #Word2Vec 을 위한 전처리

In [139]:
from gensim.models import word2vec

model = word2vec.Word2Vec(sents, size=200,window=10,hs=1,min_count=2,sg=1)

print(list(model.wv.vocab.keys()))
print("vocab length : %d"%len(model.wv.vocab))

print(model.wv.most_similar("형식"))

['무정', '경성', '학교', '영어', '교사', '이형식', '오후', '두시', '시간', '마치', '유월', '안동', '장로', '간다', '선형', '명년', '미국', '유학', '가기', '준비', '차로', '매일', '빙하', '오늘', '세시', '시작', '여자', '가까이', '교제', '청년', '모양', '대하', '자연', '생각', '얼굴', '고개', '저절로', '남자', '핑계', '어서', '한마디', '사람', '형식', '여러', '가지', '우선', '처음', '인사', '잠시', '자라', '무슨', '차별', '저편', '먼저', '그것', '교수', '방법', '어제', '청탁', '지금껏', '건마는', '가운데', '책상', '하나', '거기', '마주', '입김', '서로', '이마', '아래', '무릎', '하렷다', '혼자', '빙긋', '만일', '마음', '어찌', '대로', '멀리', '깜짝', '냄새', '실례', '점심', '담배', '불어', '손바닥', '반사', '코로', '시험', '아뿔싸', '어찌하여', '주먹', '불끈', '전신', '주어', '가슴속', '불길', '일어난다', '어디', '소리', '신우선', '대팻밥', '모자', '활개', '자기', '마음속', '보지', '한번', '겨우', '참고', '구려', '일전', '허교', '약속', '얼마', '수치', '익숙', '말끝', '대관절', '맥주', '한잔', '사나이', '가세', '파출소', '청국', '요릿집', '다른', '사양', '마는', '가슴', '경우', '다만', '볼일', '만이', '려니', '워낙', '거짓말', '한참', '개인', '유심', '부신', '듯이', '지고', '축하', '이나', '약혼', '아무', '여보', '구두', '자네', '로라', '작년', '정신', '우등', '졸업', '처녀', '신문기자', '언제', '엥게지먼트', '아따', '이면', '미인',

In [133]:
from gensim.models import Word2Vec
import pandas

In [134]:
wv = model.wv #Word2Vec model
# del(model)
# 전달받은 sigwords 중 model에 포함된 단어를 우선순위 순서로 추려냄
sigvocs = []
missvocs = []
hit = 0
miss = 0
for worddic in tfidf_dict:
    try:
        word = worddic
        if wv.vocab[word]:
            sigvocs.append(word)
            hit += 1
        if hit >= length:
            break
    except:
        missvocs.append(word)
        miss += 1
# 디버깅용. 추후 삭제.
print("missed: %d"  % miss)
for voc in missvocs:
    print(voc)


# 디스턴스 매트릭스를 데이터프레임 형태로 만듦
distDF =  pandas.DataFrame(columns = sigvocs , index = sigvocs)
for i in sigvocs:
    dists = []
    for j in sigvocs:
        dist = round(wv.distance(i, j), 6)
        dists.append(0 if dist < 1.0e-2 else dist)
    distDF[i] = dists
print(distDF)

missed: 20
고개
기생
노파
듯이
마음
모양
무슨
보고
사람
사랑
생각
선형
소리
얼굴
영채
우선
자기
지금
학생
형식
          고개        기생        노파        듯이        마음        모양        무슨  \
고개  0.000000  1.030710  0.917333  0.869951  0.996068  1.042294  0.942919   
기생  1.030710  0.000000  0.860169  0.984374  1.063709  1.046081  0.926577   
노파  0.917333  0.860169  0.000000  0.863406  0.988884  0.899526  0.977770   
듯이  0.869951  0.984374  0.863406  0.000000  0.963300  1.012499  0.958289   
마음  0.996068  1.063709  0.988884  0.963300  0.000000  1.087833  1.006858   
모양  1.042294  1.046081  0.899526  1.012499  1.087833  0.000000  1.100078   
무슨  0.942919  0.926577  0.977770  0.958289  1.006858  1.100078  0.000000   
보고  1.003436  1.048584  0.955889  1.056593  1.104400  1.022501  1.041156   
사람  0.881180  1.051776  0.950971  1.014888  1.040390  0.845946  1.078125   
사랑  1.035868  0.969464  1.012888  1.163558  1.063028  0.979234  1.012549   
생각  0.974664  0.938966  1.007562  0.985454  1.081825  1.073305  0.845395   
선형  1.025191  0.9

In [135]:
print(distDF)

          고개        기생        노파        듯이        마음        모양        무슨  \
고개  0.000000  1.030710  0.917333  0.869951  0.996068  1.042294  0.942919   
기생  1.030710  0.000000  0.860169  0.984374  1.063709  1.046081  0.926577   
노파  0.917333  0.860169  0.000000  0.863406  0.988884  0.899526  0.977770   
듯이  0.869951  0.984374  0.863406  0.000000  0.963300  1.012499  0.958289   
마음  0.996068  1.063709  0.988884  0.963300  0.000000  1.087833  1.006858   
모양  1.042294  1.046081  0.899526  1.012499  1.087833  0.000000  1.100078   
무슨  0.942919  0.926577  0.977770  0.958289  1.006858  1.100078  0.000000   
보고  1.003436  1.048584  0.955889  1.056593  1.104400  1.022501  1.041156   
사람  0.881180  1.051776  0.950971  1.014888  1.040390  0.845946  1.078125   
사랑  1.035868  0.969464  1.012888  1.163558  1.063028  0.979234  1.012549   
생각  0.974664  0.938966  1.007562  0.985454  1.081825  1.073305  0.845395   
선형  1.025191  0.958066  0.893750  0.972379  1.012556  1.073673  1.059348   
소리  1.077506

In [142]:
print(model.most_similar(positive=['무정']))

[('하니', 0.2109169214963913), ('미국', 0.20548668503761292), ('성미', 0.20517446100711823), ('지방', 0.20483292639255524), ('시늉', 0.1938799023628235), ('조화', 0.19330111145973206), ('구멍', 0.19096794724464417), ('세월', 0.19040201604366302), ('대가리', 0.18572953343391418), ('쓰기', 0.18296381831169128)]


c:\users\sun\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


In [57]:
import pandas as pd
pd.options.mode.chained_assignment = None

import numpy as np
np.random.seed(0)

from konlpy.tag import Twitter
twitter = Twitter()

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from sklearn.feature_extraction.text import HashingVectorizer

c:\users\sun\appdata\local\programs\python\python37\lib\site-packages\konlpy\tag\_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


In [58]:
def tokenizer(raw, pos=["Noun","Alpha","Verb","Number"], stopword=[]):
    return [
        word for word, tag in twitter.pos(
            raw, 
            norm=True,   # normalize 그랰ㅋㅋ -> 그래ㅋㅋ
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

In [59]:

file = open('./mujung.txt','r',encoding='utf-8')
raw_lines = file.readlines()

# 2. 변수 rawdata 저장
rawdata = []
for line in raw_lines:
    rawdata.append(line)

In [60]:
print(rawdata)

['이광수 <무정>\n', '\n', '\n', '1\n', '경성학교 영어 교사 이형식은 오후 두시 사년급 영어 시간을 마치고 내려쪼이는 유월 볕에 땀을 흘리면서 안동 김장로의 집으로 간다. 김장로의 딸 선형(善馨)이가 명년 미국 유학을 가기 위하여 영어를 준비할 차로 이형식을 매일 한 시간씩 가정교사로 고빙하여 오늘 오후 세시부터 수업을 시작하게 되었음이라. 이형식은 아직 독신이라, 남의 여자와 가까이 교제하여 본 적이 없고 이렇게 순결한 청년이 흔히 그러한 모양으로 젊은 여자를 대하면 자연 수줍은 생각이 나서 얼굴이 확확 달며 고개가 저절로 숙여진다. 남자로 생겨나서 이러함이 못생겼다면 못생겼다고도 하려니와, 여자를 보면 아무러한 핑계를 얻어서라도 가까이 가려 하고, 말 한마디라도 하여 보려 하는 잘난 사람들보다는 나으리라. 형식은 여러 가지 생각을 한다. 우선 처음 만나서 어떻게 인사를 할까. 남자 남자 간에 하는 모양으로, ‘처음 보입니다. 저는 이형식이올시다’ 이렇게 할까. 그러나 잠시라도 나는 가르치는 자요, 저는 배우는 자라, 그러면 미상불 무슨 차별이 있지나 아니할까. 저편에서 먼저 내게 인사를 하거든 그제야 나도 인사를 하는 것이 마땅하지 아니할까. 그것은 그러려니와 교수하는 방법은 어떻게나 할는지. 어제 김장로에게 그 청탁을 들은 뒤로 지금껏 생각하건마는 무슨 묘방이 아니 생긴다. 가운데 책상을 하나 놓고, 거기 마주앉아서 가르칠까. 그러면 입김과 입김이 서로 마주치렷다. 혹 저편 히사시가미(양갈래로 딴 머릿단)가 내 이마에 스칠 때도 있으렷다. 책상 아래에서 무릎과 무릎이 가만히 마주 닿기도 하렷다. 이렇게 생각하고 형식은 얼굴이 붉어지며 혼자 빙긋 웃었다. 아니 아니? 그러다가 만일 마음으로라도 죄를 범하게 되면 어찌하게. 옳다? 될 수 있는 대로 책상에서 멀리 떠나 앉겠다. 만일 저편 무릎이 내게 닿거든 깜짝 놀라며 내 무릎을 치우리라. 그러나 내 입에서 무슨 냄새가 나면 여자에게 대하여 실례라, 점심 후에는 아직 담배는 아니 먹었건마

In [61]:
vectorize = HashingVectorizer(
    tokenizer=tokenizer,
    n_features=7               # 기본 feature 수를 설정하며 기본값이 2의 20승이다. 아래 예시를 위해 feature 를 7로 한정했으나, 아래 유사문장을 찾을때는 다시 n_features 주석처리 했다.
)
X = vectorize.fit_transform(rawdata)
 
print(X.shape)
 
print(X.toarray())

(2251, 7)
[[-0.70710678  0.70710678  0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [-0.80178373  0.          0.         ...  0.53452248  0.
   0.26726124]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.40824829 ...  0.          0.40824829
  -0.81649658]]


In [64]:

# search 문장 벡터
srch_vector = vectorize.transform([
    '영채 형식'
])
 
print(srch_vector.shape)
# (1, 7)


(1, 7)


In [65]:
from sklearn.metrics.pairwise import linear_kernel
 
# linear_kernel는 두 벡터의 dot product 이다.
cosine_similar = linear_kernel(srch_vector, X).flatten()
# cosine_similar = (srch_vector*X.T).toarray().flatten()
 
print(cosine_similar)
# [0.         0.         0.62017367 0.31622777 0.3]
 
print(cosine_similar.shape)
# (5,)
 
# 유사한 rawdata index
sim_rank_idx = cosine_similar.argsort()[::-1]
print(sim_rank_idx)
#[2 3 4 1 0]
 
for i in sim_rank_idx:
    if cosine_similar[i] > 0:
        print('{} / score : {}'.format(rawdata[i], cosine_similar[i]))

[0. 0. 0. ... 0. 0. 0.]
(2251,)
[2177  782 1856 ... 1237  136 1445]
형식은 숙였던 고개를 들어,
 / score : 0.9999999999999998
“들어오시지요. 내 집이나 다름없습니다” 한다. 그 어린 기생은 그제야 문 밖에 어떤 사람이 있는 줄을 알고 고개를 기울여 형식을 본다. 형식은 그 좀 두터운 듯한 눈껍질이 곱다 하면서,
 / score : 0.9999999999999998
“가서 영채 씨 좀 보고 오겠네.”
 / score : 0.9999999999999998
형식은 김장로 집에서 나와서 바로 교동 자기 객주로 돌아왔다. 마치 술취한 사람 모양으로 아무 생각도 없이, 어디로 가는지도 모르고, 다만 일년 넘어 다니던 습관으로 집에 왔다. 말하자면 형식이가 온 것이 아니요, 형식의 발이 형식을 끌고 온 모양이라.
 / score : 0.9799578870122225
형식은 노파의 뒤를 따라 어떤 깨끗한 기와집 대문 밖에 섰다. 아직 국태민안(國泰民安)이라고 쓴 대문은 열리지 아니하였다. 노파는 마치 자기 집 사람을 부르는 모양으로,
 / score : 0.970725343394151
영채는 저도 제 생각을 모르는 모양으로 한참이나 생각하더니,
 / score : 0.9428090415820632
“여봅시오, 이 일을 어찌해요?” 하고 형식과 우선의 눈을 번갈아 본다. 노파의 일생에 남의 일을 위하여 이처럼 진정으로 슬퍼하고 걱정하고 마음이 괴로워하기는 처음이라. 노파는 어젯저녁에 진정으로 영채를 안고 울던 생각을 하였다. 그때에 영채가 생각하던 바와 같이 노파가 진정으로 남을 위하여 눈물을 흘린 것은 그때가 처음이었다. 영채의 입술에서 흐르는 피가 따끈따끈하게 노파의 손등에 떨어질 때에, 또 영채가 “남들이 다 내 살을 뜯어먹으니 나도 내 살을 뜯어먹으렵니다” 하고 피 나는 입술을 더욱 꼭꼭 물어뜯을 때에 노파의 마음은 진실로 거북하였었다. 그때에 노파가 영채의 뺨에다 자기의 뺨을 대고 엉엉 소

In [66]:
###################################연관분석

In [67]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [68]:
import numpy as np
import pandas as pd
from apyori import apriori

In [56]:
association_rules = apriori(sentences_tag,min_support=0.0053, min_confidence=0.20, min_lift=3, min_length=2)